openapi: 3.1.0

info:
  version: '1.0.0'
  title: 'E-Commerce API'
  description: 'API for managing brands, products, and user cart'

servers:
  - url: http://localhost:3000/api

paths:
  /brands:
    get:
      summary: Get all brands
      responses:
        '200':
          description: An array of brands

  /brands/{id}/products:
    get:
      summary: Get products by brand
      responses:
        '200':
          description: An array of products

  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: An array of products

  /login:
    post:
      summary: Login a user
      reponses:
        '200':
          description: Token

  /me/cart:
    get:
      summary: Return contents of users cart
      responses:
        '200':
          description: An array of products

    post:
      summary: Add product to users cart
      responses:
        '200':
          description: An array of products

  /me/card/{productId}:
    delete:
      summary: Remove product from users cart
      responses:
        '200':
          description: An array of products

  /me/cart/{productId}:
    post:
      summary: Update quantity of product in users cart
      responses:
        '200':
          description: An array of products

components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: integer
        categoryId:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
        imageUrls:
          type: array
          items:
            type: string
    Users:
      type: object
      properties:
        gender:
          type: string
          enum: [male, female]
        cart:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        name:
          type: object
          properties:
            title:
              type: string
            first:
              type: string
            last:
              type: string
        location:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            postcode:
              type: integer
        email:
          type: string
          format: email
        login:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
            salt:
              type: string
            md5:
              type: string
            sha1:
              type: string
            sha256:
              type: string
        dob:
          type: string
          format: date-time
        registered:
          type: string
          format: date-time
        phone:
          type: string
        cell:
          type: string
        picture:
          type: object
          properties:
            large:
              type: string
              format: uri
            medium:
              type: string
              format: uri
            thumbnail:
              type: string
              format: uri
        nat:
          type: string
          description: Nationality code (e.g., "IE" for Ireland)
